dll:
  - Sources/**/*
  - Sources/*

tool:
  - Tools/**/*

xml:
  - Assets/**/*.xml

text:
  - Assets/XML/Text/**/*
  - Assets/Modules/**/*Text*.xml

python:
  - Assets/Python/**/*

art:
  - UnpackedArt/**/*
  - ArtSource/**/*
  - Assets/art/**/*

audio:
  - Assets/Sounds/**/*

