dll:
  - Sources/**/*

tool:
  - Tools/**/*

xml:
  - Assets/**/*.xml

text:
  - Assets/XML/Text/**/*

python:
  - Assets/Python/**/*

art:
  - UnpackedArt/**/*
  - ArtSource/**/*
  - Assets/art/**/*

audio:
  - Assets/Sounds/**/*

