version: 40.0.{build}
image: Visual Studio 2019

environment:
  svn_url: https://svn.code.sf.net/p/c2c-gittest/code/trunk/
  svn_user: c2cappveyor
  svn_pass:
    secure: mMXMYcNOGLSRmTCfng6QU8yFa84Stb35a4spzhscQC0=
  release_prefix: Caveman2Cosmos
  build_dir: _build

build_script:
- cmd: >-
    call "%APPVEYOR_BUILD_FOLDER%\Tools\MakeDLLDebug.bat"

    call "%APPVEYOR_BUILD_FOLDER%\Tools\MakeDLLRelease.bat"

test_script:
- cmd: >-
    cd Tools

    XmlValidator.exe -a

artifacts:
- path: $(release_prefix)-$(APPVEYOR_BUILD_VERSION).zip
  name: Caveman2Cosmos
- path: $(release_prefix)-CvGameCoreDLL-$(APPVEYOR_BUILD_VERSION).zip
  name: Caveman2CosmosDLL

before_deploy:
- cmd: call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

deploy:
- provider: GitHub
  auth_token:
    secure: gh2SyyG2KoAG4DwS6vg6my4mb/83P0aCfDJNyry0ncMapKqALE0GHR+f7EqwZkn2M712UhRYiyxXq0UU4/4hh5c6W4loKDYh/w5VOclmSfY=
  artifact: Caveman2Cosmos,Caveman2CosmosDLL
  prerelease: true
  force_update: true
  on:
    branch: test-deployment

notifications:
- provider: Slack
  incoming_webhook:
    secure: /rZsiy2rHhDaEh9f3Hzv6RtkcI/grO+svFlzo0AErpTBOfM0e2IDGzUVemKjvU2uQhUIL+t9TgYCItXIAcTIlAuZUgbXxJJGTQn4eJ+tkgM0Ze6dt+JSvb3H5nndmk9epWUr89PASEMdwTgw3nuJJe4f7TveskQwWbS1XNEX0lF5i/B8wj+TS5uIqZQPD/wP
  channel: github
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
