version: 40.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2019
environment:
  svn_url: https://svn.code.sf.net/p/c2c-gittest/code/
  svn_user: c2cappveyor
  svn_pass:
    secure: mMXMYcNOGLSRmTCfng6QU8yFa84Stb35a4spzhscQC0=
build_script:
- cmd: >-
    call Tools\MakeDLLDebug.bat

    call Tools\MakeDLLRelease.bat
test_script:
- cmd: >-
    cd Tools

    XmlValidator.exe -a
notifications:
- provider: Slack
  incoming_webhook:
    secure: /rZsiy2rHhDaEh9f3Hzv6RtkcI/grO+svFlzo0AErpTBOfM0e2IDGzUVemKjvU2uQhUIL+t9TgYCItXIAcTIlAuZUgbXxJJGTQn4eJ+tkgM0Ze6dt+JSvb3H5nndmk9epWUr89PASEMdwTgw3nuJJe4f7TveskQwWbS1XNEX0lF5i/B8wj+TS5uIqZQPD/wP
  channel: github
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false