version: 40.0.{build}
image: Visual Studio 2019
cache:
- Build\Debug -> Tools\deps.exe, Tools\_MakeDLL.bat, Sources\, appveyor.yml
- Build\Release -> Tools\deps.exe, Tools\_MakeDLL.bat, Sources\, appveyor.yml

environment:
  testing: true
  svn_url: https://svn.code.sf.net/p/caveman2cosmos/code/trunk
  svn_test_url: https://svn.code.sf.net/p/caveman2cosmos/code/branches/billw-git
  svn_user: c2cappveyor
  svn_pass:
    secure: 8MBckNYRp5EVPgbGcmZ6bQ==
  git_user: c2cappveyor
  git_email: 
    secure: XNL5MWZKrsIcIJE56OhImjxBF2h9Kkub+hQJK9m73WA=
  git_access_token:
    secure: c5g3VzEHFNptNDFyI85sEbUyI5fNW5rHwovptE64l2GmzUJ2bcgzTbzsa7Y90jKa
  release_prefix: Caveman2Cosmos
  build_dir: _build
  release_branch: release
  # nodejs_version: "11"

install:
  # Get the latest stable version of Node.js or io.js
  # Need this for deploy script 
  # - ps: Install-Product node $env:nodejs_version
  # - npm install auto-changelog
  - set PATH=C:\Ruby26-x64\bin;%PATH%
  - gem install github_changelog_generator

build_script:
- cmd: >-
    github_changelog_generator --cache-file "github-changelog-http-cache" --cache-log "github-changelog-logger.log" -u caveman2cosmos --token %git_access_token% --future-release %version% --release-branch %release_branch% --output "%build_dir%\CHANGELOG.md"

    call Powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%APPVEYOR_BUILD_FOLDER%\Tools\CI\fix_sources_timestamps.ps1"
    
    call "%APPVEYOR_BUILD_FOLDER%\Tools\_MakeDLL.bat" build Debug

    call "%APPVEYOR_BUILD_FOLDER%\Tools\_MakeDLL.bat" build Release

test_script:
- cmd: >-
    cd Tools

    XmlValidator.exe -a

# DISABLED: before_deploy can't access secure variables it seems
# before_deploy:
# - cmd: >-
#     call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

#     echo %secure_test%

deploy_script:
- cmd: >-
    call "%APPVEYOR_BUILD_FOLDER%\Tools\CI\DeployBuild.bat"

# DISABLED: this doesn't work, unauthorized
# deploy:
# - provider: GitHub
#   auth_token:
#     secure: 8q/T1sjdSGdr8NWfFwisFuaMGNT5v4fKCZiS98tDQtFhbbOu2nmPSclfRfFsDE4Y
#   artifact: $(release_prefix)-$(APPVEYOR_BUILD_VERSION).zip,$(release_prefix)-CvGameCoreDLL-$(APPVEYOR_BUILD_VERSION).zip
#   prerelease: true
#   on:
#     branch: test-deployment

notifications:
- provider: Slack
  incoming_webhook:
    secure: /rZsiy2rHhDaEh9f3Hzv6RtkcI/grO+svFlzo0AErpTBOfM0e2IDGzUVemKjvU2uQhUIL+t9TgYCItXIAcTIlAuZUgbXxJJGTQn4eJ+tkgM0Ze6dt+JSvb3H5nndmk9epWUr89PASEMdwTgw3nuJJe4f7TveskQwWbS1XNEX0lF5i/B8wj+TS5uIqZQPD/wP
  channel: github
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
